# Site settings
title: Koen De Couck Homepage
email: koen.decouck@outlook.com
description: "Koen De Couck is a big data Hadoop consultant from Belgium"
baseurl: ""
url: "https://koendecouck.github.io"
future: true

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/
paginate: 10

# Gems
gems: [jekyll-paginate]
